### ISSUE TITLE
subview send to back

### ISSUE THREAD

**Issue by lucasfeliciano** [Scandit/BarcodeScannerPlugin#28]
Hello there,

I want to make the scandit view to be behind of my cordova's app webview. 
How can I do that?

**Comment by moritz-scandit** [comment]
If the scanner were behind the webview you could not see it, because it is hidden by the webview. I doubt that this is what you want to do. I assume what you want is to have the webview as a kind of overlay of the scanner where the scanner pokes through at transparent places, this is something that is not possible with PhoneGap.

**Comment by lucasfeliciano** [comment]
But there is a way to hack it using native code in the plugin?
If I write those functions it will work, right?

**Comment by moritz-scandit** [comment]
You could potentially set the webview background to transparent and add the scanner behind it in the view hierarchy, any interaction with the scanner would then be gone though. You are free to try to do something like this but we will not be able to help you in any way with this endeavor.

**Comment by lucasfeliciano** [comment]
Cool, that will work for me.
I don't need interactions with the scanner :)
And by the way, the new sdk is awesome.
