### ISSUE TITLE
Error while executing install command from terminal

### ISSUE THREAD

**Issue by Sampurna20** [Scandit/BarcodeScannerPlugin#56]
I have tried installing your plugin with the below command:
sudo cordova plugin add https://github.com/Scandit/BarcodeScannerPlugin

There was an error displayed in between installation:
root/ApplicationCode/plugins/com.mirasense.scanditsdk.plugin/src/android/scanditsdk-community-android_4.0.0/ScanditBarcodeScanner.aar" not found!

Please let me know what have I missed in the installation process?

**Comment by moritz-scandit** [comment]
Hi,
As the repository's readme states the repository does not contain all needed components of the plugin:

Important: This repository does not contain the core library of the Scandit Barcode Scanner since the library can not be publicly distributed. It only contains the classes that wrap the library to create a PhoneGap plugin and is therefore not an installable PhoneGap plugin. The actual library is only available from your Scandit account where you can download the fully installable PhoneGap plugin that includes the libraries.
