### ISSUE TITLE
Camera permissions on Android 6 

### ISSUE THREAD

**Issue by kylex** [Scandit/BarcodeScannerPlugin#57]
I'm using 4.14.0
I'm unsure why, but Scandit fails to request camera permissions on Android 6.
Is there a specific setting I need to turn on for this?

**Comment by biasmv** [comment]
Hi kylex,

4.14 does not yet contain any code to handle camera permissions at runtime As a simple workaround, you can change the target SDK level in the AndroidManifest.xml file to a target API level lower than 23. This will effectively turn off the runtime permission request behaviour you are seeing now.

We have implemented runtime camera permission request handling for the next release, so starting from 4.15 this will no longer be necessary.

Hope that helps.

Best,
Marco

**Comment by kylex** [comment]
Got it, thanks!

**Comment by tuongaz** [comment]
Hi Marco,

When I changed the target SDK level to 22, it got this error when installing the app:

INSTALL_FAILED_PERMISSION_MODEL_DOWNGRADE

When I removed the app from device and installed again, it worked. However, what happens if I set target SDK level = 22 and deploy the app to the Play Store, will the devices have the app running with SDK level = 23 can upgrade the app?

**Comment by biasmv** [comment]
I'd suggest you update to the latest version of the barcode scanner SDK.

Starting from version 4.15 we support runtime permission request handling on Android. Setting the target SDK level to 22 is no longer required if you use 4.15 (or 4.16 which was released last week). 

I hope that helps.

Best,
Marco
