### ISSUE TITLE
switchTorchOn not working on Android

### ISSUE THREAD

**Issue by keithdmoore** [Scandit/BarcodeScannerPlugin#59]
Here is the code below.  This works on iOS but it does NOT work on Android.  Changed the location of the `switchTorchOn` call to before show and after `startScanning` and that does NOT work for Android.

````
            // Display the scanner
            this._picker.show(session => {
              console.log('barcode', text: session.newlyRecognizedCodes[0].data);
            }, null, errorMsg => {
              console.error(`Scan failed with error: ${errorMsg}`);
            });

            // Turn on flashlight/torch
            this._picker.switchTorchOn(true);
            
            // Start scanning and show video feed.
            this._picker.startScanning();
````

**Comment by moritz-scandit** [comment]
Hi Keith,

I assume that you are displaying the scanner fullscreen where the issue is that the Activity takes a bit until it is created which causes the torch call to go into nothingness. I fixed the issue with https://github.com/Scandit/BarcodeScannerPlugin/commit/abda6e184b50f62e4709bd326267ad838772fbba. You can add the fix to your local plugin, wait for the next release or what you can also do as a work around is use it with setTimeout to start the torch after some 100ms.
